# All contributions are important small and big
# To try giving back to the top contributors, abapGit will feature the top 4 contributor links. The links will be updated
# on a half year basis
# based on https://github.com/abapGit/abapGit/graphs/contributors?from=2020-01-01&to=2020-11-03&type=c
# the below are the top 4 contributors to abapGit for 2020
custom: sbcg.com.ua
github: [christianguenter2, mbtools, larshp]
