---
parserOptions:
  ecmaVersion: 5
env:
  browser: true
extends:
  - eslint:recommended
rules:
  quotes: ['error', 'double', { 'avoidEscape': true }]
  semi:   ['error', 'always', { 'omitLastInOneLineBlock': true}]
  no-console: off
  indent: ['error', 2]
  no-trailing-spaces: ['error']
  no-unused-vars: ['warn']
