#
# CI for repository
#
stages:
  - init
  - pull
  - push
  - test

include:
  - project: 'tools/abapgit-extensions'
    ref: master
    file: '/ci-include.yml'

init:
  extends: .info_pipeline
  stage: init

abaplint:
  stage: test
  extends: .abaplint

do-pull:
  stage: pull
  extends: .do-pull-master

do-push:
  stage: push
  extends: .do-fork-push-master
