language: node_js
node_js:
  - "6"
notifications:
  email: false
deploy:
  provider: script
  script: ./travis.sh
  skip_cleanup: true
  on:
    branch: abapmarge
env:
  global:
    secure: "Spy5/ate1dljTzKBuGtGxE7vHbDqtISheaRvkS1j8C85mHseT0aIzQ/g1PIQC0IOARkqnawhbugFDQgjguVURRbW56nHrpJq1q1EB6Hz8cEXuVvhb82A4mPnNcjszFqhpKpT6RCSZnEjpMES78cvEoFMDsDkn9bI6keKpS3bFo1TweHkGEeHnVeBJChhISK3Y5i7HjGlbFDFNjlg4ku7B6l8LXtrBkQrY/NTAtgMAihyoFGFjanhYiFxnb6A5NkY2XZjw134buHmqzbz/W8WIU9BDIbGDOqhnOyC5AsUrLGLO9LA+UI0Ep82nNDMrhJpntMMeB60OrbK8LJVhGK01dEcQhmXydjar/HLjVYEYiN/conyvF7zpvqqtgpS4pK8Ean9dhcd19gfdkJ93swiKPcz55x59G7o1b3Ons32uEBnkEu4CB4gq0v1RgWCnUXkJkzhQZvcpWMzaqvzNiY6K+xqTQTcHdAaltQ9rumeWnrHuVsIAzKp+mFdqhjKytCJAbePToGK39PUER4AWkgv2sKSm7je1tMsBcqEBxFY/ExkKHO0ue2Zr/J5sl3Yw+yL/qbHL7tmT2Q6RdcDoSTZ+oNhEgCPKKRyq5UjrIzPIJeZ7GaCcXV0jBeakaCsak5zMRMdB04bw7jonMoFaA9kTihsTii37Nk1/PPEGLvI01A="
