language: node_js
node_js:
  - "10"
notifications:
  email: false
deploy:
  provider: script
  script: ./travis.sh
  skip_cleanup: true
  on:
    branch: master
env:
  global:
    secure: "D/S7H+yUP/qGpKubya8Tw/IZc5R5Oq3BEq4tE6+PHtLrSrNh0mwVIiZV2rXQbGU2rgNFE3GRJwLBWsS6X5GMvinZrfmns7BpLS+AIxO0T+oIEBM7SdTfLVaic2reHH+5jvS/+TKMYyjjjAyXli/0FPfAxFtVLSuoNYOlZLAc3E0RncvEk+3PvxNw29k6RfKQgE1ZEqwPKtT2KytkFq0a6FCdoJxdu6kpCJt4krT+etgWPp3WlURqg7GGNVs6M0CzOVYNSdS9Azy/Q+ureXQsAQz0r0txPGC1B7VS5Kf69AvBr8HIMsTmO3UbN/WxPsEnH2aECzTnDFQ58WtW3gONnX4Z2MrfVkZFuTaJNUmD6z0H1p9lIMRwSzme57kpKBPGY4KrHmFH4ppdsgO3AKj+MqioogRW/k97Odv/OZmzDc1QC1i49iyI+9IlSXtMziXUlREzBh16DiKOZT15oBerAxTUw9dAzIW7Ec0XVIFhBYwtYFXO4tovlc2J5yLwIS4pxyquurEDqMhwO/4DQHT02K/M8oIR9RWwZY+mU/TxGrHGDKJjk7/KiYj9fJXE2G6aDE43f4bB6EF+5DzM3DD9NpcpE6Dj5MFNO6Bc03tupGGL4ZJKSQiENS701bVKavJ+JU2I0ip07szjRB7NSeN97P3EhlnjUA86+qCDr4CdziY="
