version = 1

[[annotations]]
path = "**"
SPDX-FileCopyrightText = "2014 abapGit Contributors <https://abapgit.org>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "src/ui/zabapgit_icon_font*"
SPDX-FileCopyrightText = "2021 Font Awesome <https://fontawesome.com/>"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "src/json/**/*"
SPDX-FileCopyrightText = "2020 Alexander Tsybulsky <https://github.com/sbcgua/ajson>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "src/stringmap/**/*"
SPDX-FileCopyrightText = "2020 Alexander Tsybulsky <https://github.com/sbcgua/abap-string-map>"
SPDX-License-Identifier = "MIT"
