CLASS zcl_abapgit_sap_package_test DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_abapgit_sap_package_test IMPLEMENTATION.
ENDCLASS.
