CLASS ltcl_smtg DEFINITION DEFERRED.
CLASS zcl_abapgit_object_smtg DEFINITION LOCAL FRIENDS ltcl_smtg.

CLASS ltcl_smtg DEFINITION FOR TESTING RISK LEVEL HARMLESS DURATION SHORT.

  PRIVATE SECTION.
    METHODS:
      get_xml RETURNING VALUE(rv_xml) TYPE string,
      deserialize_xml_into_aff FOR TESTING RAISING cx_static_check.

ENDCLASS.


CLASS ltcl_smtg IMPLEMENTATION.

  METHOD deserialize_xml_into_aff.

    DATA:
      ls_smtg     TYPE zif_abapgit_aff_smtg_v1=>ty_main,
      lv_json     TYPE string,
      lv_expected TYPE string,
      lv_xstr     TYPE xstring,
      lo_input    TYPE REF TO zcl_abapgit_xml_input,
      lo_handler  TYPE REF TO zcl_abapgit_json_handler.

    CREATE OBJECT lo_input
      EXPORTING
        iv_xml = get_xml( ).

    ls_smtg = zcl_abapgit_object_smtg=>deserialize_xml_to_aff( lo_input ).

    CREATE OBJECT lo_handler.
    lv_xstr = lo_handler->serialize( ls_smtg ).
    lv_json = cl_abap_codepage=>convert_from( lv_xstr ).

    lv_expected =
      `{` && cl_abap_char_utilities=>newline &&
      `  "formatVersion": "1",` && cl_abap_char_utilities=>newline &&
      `  "header": {` && cl_abap_char_utilities=>newline &&
      `    "description": "test",` && cl_abap_char_utilities=>newline &&
      `    "originalLanguage": "en"` && cl_abap_char_utilities=>newline &&
      `  },` && cl_abap_char_utilities=>newline &&
      `  "generalInformation": {` && cl_abap_char_utilities=>newline &&
      `    "templateDescription": "This is a test",` && cl_abap_char_utilities=>newline &&
      `    "cdsView": "I_USER",` && cl_abap_char_utilities=>newline &&
      `    "isPredelivered": true,` && cl_abap_char_utilities=>newline &&
      `    "emailSubject": "Hallo {{UserID}}{{UserDescription}}",` && cl_abap_char_utilities=>newline &&
      `    "isPlaintextAutoGenerated": true` && cl_abap_char_utilities=>newline &&
      `  },` && cl_abap_char_utilities=>newline &&
      `  "templateContent": [` && cl_abap_char_utilities=>newline &&
      `    {` && cl_abap_char_utilities=>newline &&
      `      "name": "Body HTML"` && cl_abap_char_utilities=>newline &&
      `    },` && cl_abap_char_utilities=>newline &&
      `    {` && cl_abap_char_utilities=>newline &&
      `      "name": "Body Plain Text"` && cl_abap_char_utilities=>newline &&
      `    }` && cl_abap_char_utilities=>newline &&
      `  ]` && cl_abap_char_utilities=>newline &&
      `}` && cl_abap_char_utilities=>newline.

    cl_abap_unit_assert=>assert_equals(
      act = lv_json
      exp = lv_expected ).

  ENDMETHOD.


  METHOD get_xml.

    DATA lv_newline TYPE c LENGTH 1.

    lv_newline = cl_abap_char_utilities=>newline.

    rv_xml =
      `<?xml version="1.0" encoding="utf-8"?>` && lv_newline &&
      `<abapGit version="v1.0.0" serializer="LCL_OBJECT_SMTG" serializer_version="v1.0.0">` && lv_newline &&
      ` <asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0">` && lv_newline &&
      `  <asx:values>` && lv_newline &&
      `   <SMTG>` && lv_newline &&
      `    <HEADER>` && lv_newline &&
      `     <ID>ZTEST_TEMPLATE</ID>` && lv_newline &&
      `     <VERSION>A</VERSION>` && lv_newline &&
      `     <CDS_VIEW>I_USER</CDS_VIEW>` && lv_newline &&
      `     <IS_PREDELIVERED>X</IS_PREDELIVERED>` && lv_newline &&
      `     <SMTG_VERSION>1</SMTG_VERSION>` && lv_newline &&
      `    </HEADER>` && lv_newline &&
      `    <HEADER_T>` && lv_newline &&
      `     <SMTG_TMPL_HDR_T>` && lv_newline &&
      `      <ID>ZTEST_TEMPLATE</ID>` && lv_newline &&
      `      <VERSION>A</VERSION>` && lv_newline &&
      `      <LANGU>E</LANGU>` && lv_newline &&
      `      <NAME>test</NAME>` && lv_newline &&
      `      <DESCRIPTION>This is a test</DESCRIPTION>` && lv_newline &&
      `     </SMTG_TMPL_HDR_T>` && lv_newline &&
      `    </HEADER_T>` && lv_newline &&
      `    <CONTENT>` && lv_newline &&
      `     <SMTG_TMPL_CONT>` && lv_newline &&
      `      <ID>ZTEST_TEMPLATE</ID>` && lv_newline &&
      `      <VERSION>A</VERSION>` && lv_newline &&
      `      <LANGU>E</LANGU>` && lv_newline &&
      `      <SUBJECT>Hallo {{UserID}}{{UserDescription}}</SUBJECT>` && lv_newline &&
      `      <BODY_TXT>Hallo` && lv_newline &&
      `{{UserID}}{{UserDescription}}</BODY_TXT>` && lv_newline &&
      `      <BODY_HTML>&lt;b&gt;` && lv_newline &&
      `Hallo` && lv_newline &&
      `{{UserID}}{{UserDescription}}` && lv_newline &&
      `&lt;/b&gt;</BODY_HTML>` && lv_newline &&
      `      <AUTOGEN_TXT>X</AUTOGEN_TXT>` && lv_newline &&
      `     </SMTG_TMPL_CONT>` && lv_newline &&
      `    </CONTENT>` && lv_newline &&
      `   </SMTG>` && lv_newline &&
      `  </asx:values>` && lv_newline &&
      ` </asx:abap>` && lv_newline &&
      `</abapGit>`.

  ENDMETHOD.

ENDCLASS.
