CLASS ltcl_test DEFINITION DEFERRED.
CLASS zcl_abapgit_object_ssfo DEFINITION LOCAL FRIENDS ltcl_test.


CLASS ltcl_test DEFINITION FOR TESTING DURATION SHORT RISK LEVEL HARMLESS FINAL.

  PRIVATE SECTION.
    METHODS sort_texts FOR TESTING RAISING cx_static_check.
ENDCLASS.


CLASS ltcl_test IMPLEMENTATION.

  METHOD sort_texts.



  ENDMETHOD.




ENDCLASS.
