CLASS lcl_tabl_xml DEFINITION FINAL.
  PUBLIC SECTION.
    CLASS-METHODS add IMPORTING is_internal TYPE ty_internal.
ENDCLASS.

CLASS lcl_tabl_xml IMPLEMENTATION.
  METHOD add.
* todo
  ENDMETHOD.
ENDCLASS.
