CLASS ltcl_ci DEFINITION FOR TESTING RISK LEVEL CRITICAL DURATION MEDIUM.
  PUBLIC SECTION.
    METHODS run FOR TESTING.
ENDCLASS.

CLASS ltcl_ci IMPLEMENTATION.
  METHOD run.
    zcl_abapgit_objects_ci_tests=>run( 'TABL' ).
  ENDMETHOD.
ENDCLASS.
