FUNCTION-POOL zabapgit_repo_pre_filter.     "MESSAGE-ID ..

* INCLUDE LZABAPGIT_REPO_PRE_FILTERD...      " Local class definition

TABLES e070.
SELECTION-SCREEN BEGIN OF SCREEN 1001 TITLE s_tit_pf.
SELECT-OPTIONS s_trkorr FOR e070-trkorr.
SELECTION-SCREEN END OF SCREEN 1001.
