CLASS zcx_abapgit_cancel DEFINITION
  PUBLIC
  INHERITING FROM zcx_abapgit_exception
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.


CLASS ZCX_ABAPGIT_CANCEL IMPLEMENTATION.
ENDCLASS.
