title: abapGit documentation
highlighter: rouge
collections_dir: collections
collections:
  development:
    output: true
plugins:
  - jekyll-octicons    
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_development"
    values:
      layout: "development"
