name: lint

on: [push, pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: abaplint
      uses: abaplint/actions-abaplint@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
