name: test-pr

on:
  pull_request:

permissions:
  contents: read

jobs:
  lint-and-merge:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: |
        npm install
        npm run eslint
        npm run merge
        npm run merge.ci
    - name: Upload build artifact
      uses: actions/upload-artifact@main
      with:
        name: zabapgit_standalone.abap
        path: ./zabapgit.abap
        retention-days: 7

  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: npm install
    - run: npm run unit
    - run: npm run coverage

  integration:
    runs-on: ubuntu-latest
    needs: unit-tests
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: npm install
    - name: start gitea
      working-directory: test/gitea/
      run: npm install && npm run gitea
    - run: npm run integration
