name: unit_test

on: [push]

jobs:
  unit_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Run npm steps
      if: github.ref != 'refs/heads/master' && github.actor == 'larshp'
      run: |
        npm install
        npm run unit
    - name: View PR author
      run: echo "This PR is opened by ${{ github.event.pull_request.user.login }} ."